version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8080:80"
      - "8081:81"
    networks:
      - backend
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro

  service-b:
    image: node:18
    container_name: service-b
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - database

  service-c:
    image: node:18
    container_name: service-c
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "81:81"
    networks:
      - backend
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
