version: '3.9'

services:
  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "8080:80" # For app B
      - "8081:81" # For app C
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

  app_b:
    build:
      context: ./app_b
    container_name: app_b
    networks:
      - webnet
    environment:
      - DB_HOST=database
      - DB_NAME=appdb
      - DB_USER=postgres
      - DB_PASSWORD=password

  app_c:
    build:
      context: ./app_c
    container_name: app_c
    networks:
      - webnet
    environment:
      - DB_HOST=database
      - DB_NAME=appdb
      - DB_USER=postgres
      - DB_PASSWORD=password

  database:
    image: postgres:latest
    container_name: database
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data:
